os: linux
dist: focal
language: haskell

git:
  depth: 5

cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  - ghc: 8.8.3
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"
  - ghc: 8.10.1
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.nightly.yaml"

addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb http://archive.ubuntu.com/ubuntu focal universe'
    packages:
      - libjwt-dev
      - libjwt0

install:
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version
  - stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --ghc-options=-Werror

script:
  - stack test --system-ghc

